### ISSUE TITLE
Docs Structure

### ISSUE THREAD

**Issue by jesusvazquez** [slok/kahoy#129]
:wave: With the acquisition of kahoy.dev it would be great to give the project a nice looking docs site.

As we all know writing docs efficiently is extremely complex for a single person or even few people, specially if they hold all the context and lack external feedback. 

This issue is to track the progress around the future documentation structure and discussion for the site.

**Comment by jesusvazquez** [comment]
Initial structure that I have on my mind after taking a peek at the README and other online documentation sites like https://docs.fluxcd.io/en/1.21.0/get-started/

```
- Landing with few lines of text describing the project and some media like video or diagram to showcase
- Introduction about Kahoy
  - What is Kahoy
  - What can you do with Kahoy
  - Kahoy Requirements and Limitations
  - Alternatives
- Get Started
  - Install
  - Features
  - How does it work
  - Concepts
  - Manifest Source Providers
    - Git
    - Paths
    - Kubernetes
  - ...
- Use Cases
  - Dry Run on PRs 
  - Diff on CI 
  - Deploy from master 
  - ...
- Tutorials
  - Setting up Kahoy on Github Repository
  - Combining Kahoy and Helm to achieve X
  - Combining Kahoy and Kustomize to achieve Y
  - ...
- F.A.Q
```

What would you change @slok

**Comment by slok** [comment]
I like it however I would change some things, for example:

- I wouldn't add all the configuration/usage options under `- Get Started`.
- I would add a filtering resources section.

**Comment by slok** [comment]
We could also take https://helm.sh/docs/ as a good example. I've seen there a section that is pretty nice `glossary`. We could explain there in a dast and easy way things like `resource`, `provider`, `action`, `report`... with a very few words (that doesn't mean that replaces their own section/entry)
