### ISSUE TITLE
Kahoy kubectl timeout setting

### ISSUE THREAD

**Issue by jesusvazquez** [slok/kahoy#158]
It would be a good idea to introduce timeouts when applying resources in case the execution gets stuck at some point.

Ideas:
- Kubectl has a paremeter `--timeout` that we could use.
- Use context with timeout and kill the execution if its exceeded

**Comment by jesusvazquez** [comment]
> Kubectl has a paremeter --timeout that we could use.

Kubectl is only the implementation we're using to interact with the clusters. This could be replaced in the future with `client-go` or any other alternative.

For this reason I believe it would be a better idea to implement the timeouts on a higher layer of the application.

---

I've been taking a look at the code and I think we could rely on the resource Manager, actually any of the implementations since its an interface.

The manager has a method `Apply` that receives a context and a list of resources https://github.com/slok/kahoy/blob/master/internal/resource/manage/manage.go#L12

Example:
- Kubectl manager apply https://github.com/slok/kahoy/blob/a8c5acac30b63496a71b7a027a9bc818317bf119/internal/resource/manage/kubectl/kubectl.go#L111
- Kubectl execute https://github.com/slok/kahoy/blob/a8c5acac30b63496a71b7a027a9bc818317bf119/internal/resource/manage/kubectl/kubectl.go#L129

There is also the batch manager which could leverage a timeout per batch aswell.

Do you find this place appropiate @slok ?

**Comment by slok** [comment]
From the options you have exposed I think that the best one could be a timeout per execution, this is, per batch, we could say that the `delete` operation is another batch.

Regarding the implementation as you correctly point out, the manager would be the key here, this would involve creating a new [manager](https://github.com/slok/kahoy/tree/master/internal/resource/manage) called `timeout` or similar, that would wrap the original manager, using the context to add a timeout.

This timeout decorator would be used the same way we use the `wait` resource manager, wrapping the manager [before](https://github.com/slok/kahoy/blob/master/cmd/kahoy/apply.go#L260) wrapping with our priority batch manager.

In the future, we could decide if the timeout should involve the wait duration of the batch or not, but this can be changed easily at any moment.

Regarding how to enable this, we should have a flag, similar to `--batch-timeout`, in case of 0, this decorator shouldn't have any effect.

WDYT?

**Comment by jesusvazquez** [comment]
Makes sense! I'll get on to that soon.

**Comment by jesusvazquez** [comment]
PR is up for review!
