### ISSUE TITLE
Allow filtering by namespaces

### ISSUE THREAD

**Issue by slok** [slok/kahoy#50]

**Comment by jesusvazquez** [comment]
Before implementing anything I'd like to know if what I have in mind makes sense at all. So let's see if I get this right:

Running a command like this `kahoy apply --diff --include-namespace kube-system --mode paths -o /dev/null -n ./manifests` is like filtering from the list of resources those that have `namespace=<namespace>`.

If that premise is right then I think that the repository that list resources should be the one applying the filters. Let's dive
- https://github.com/slok/kahoy/blob/master/cmd/kahoy/apply.go#L95-L104
- https://github.com/slok/kahoy/blob/master/internal/storage/memory/memory.go#L42-L51
- Loading from FS https://github.com/slok/kahoy/blob/master/internal/storage/fs/fs.go#L274 and decode into k8sobject
- K8sObject https://github.com/slok/kahoy/blob/master/internal/model/resource.go#L12-L15

```
type K8sObject interface {
	runtime.Object
	metav1.Object
}
```

So things I'd do:
- Add `namespace string` to K8sObject so we load it when loading the resources.
- Repository should have `includeNamespace []*regexp.Regexp`.
- In the function `func (r *Repository) loadFS(rootPath string) error {` after loading the resource, check if we should include it or not based on namespace. Somewhere around these lines https://github.com/slok/kahoy/blob/master/internal/storage/fs/fs.go#L223-L239

WDYT?

**Comment by slok** [comment]
The approach that you describe is valid, however, couples the filtering to a single way of loading resources, and in this case, we use domain-level data to filter (k8s object namespace).

The filtering could be done outside the repository, once we have our models loaded. This decouples filtering to any type of repository, so if we implement 100 ways of loading resources, we would have ns filtering available.

Also, our `model.Resource` already has the information required, so, we don't need to add extra fields to the object, [metav1.Object](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#Object) already has `GetNamespace()`.

Take a look at these as an example:
- https://github.com/slok/kahoy/blob/master/internal/resource/process/kubemeta.go, 
- https://github.com/slok/kahoy/blob/1878d2e0c49146b32d16910c53625c6c609ea1aa/cmd/kahoy/apply.go#L287-L310

**Comment by jesusvazquez** [comment]
The examples were very helpful, check this out https://github.com/slok/kahoy/pull/122

**Comment by jesusvazquez** [comment]
Closing :tada:
